Ca feature/yml env files support
wisegrowth/pigeon pull request #9
Opened 2017-10-07 20:41 UTC by cagodoy

Added support for using yml configuration file to pigeon service.
it is also possible to define the path of the configuration file using the `--path`

2017-10-19 02:57 UTC, jaguirresza requested changes

2017-10-19 02:57 UTC, jorgeaguirre commented on cmd/scheduler/main.go
> +	DbFile           string `yaml:"db_file"`
s/DbFile/DBFile/

2017-10-19 02:57 UTC, jorgeaguirre commented on cmd/scheduler/main.go
> +	RedisIdleTimeout string `yaml:"redis_idle_timeout"`
Why is this a string?

2017-10-19 02:57 UTC, jorgeaguirre commented on cmd/scheduler/main.go
> +	Port             string `yaml:"port"`
Why is this a string?

2017-10-24 02:35 UTC, cagodoy commented on cmd/scheduler/main.go
> +	DbFile           string `yaml:"db_file"`
🐒

2017-10-24 02:41 UTC, cagodoy commented on cmd/scheduler/main.go
> +	DbFile           string `yaml:"db_file"`
@jorgeaguirre  tontito 🐒

2017-10-25 02:42 UTC, Weyker commented on cmd/scheduler/main.go
> +	DbFile           string `yaml:"db_file"`
aaa camilo, ahora cache lo q qeria decir... xD

q cambies DbFile por DBFile

mucho vim el ql

2018-10-16 23:01 UTC, closed without merging